"type: feature ✨":
  title: '^feat(\(.+\))?:.*'
"type: fix 🐞":
  title: '^fix(\(.+\))?:.*'
"type: docs 📋":
  title: '^docs(\(.+\))?:.*'
"type: style 🎨":
  title: '^style(\(.+\))?:.*'
"type: refactor 🔧":
  title: '^refactor(\(.+\))?:.*'
"type: test 🧪":
  title: '^test(\(.+\))?:.*'
"type: chore 🧹":
  title: '^chore(\(.+\))?:.*'
"type: perf ⚡":
  title: '^perf(\(.+\))?:.*'
"type: build 🔨":
  title: '^build(\(.+\))?:.*'
"type: ci ⚙️":
  title: '^ci(\(.+\))?:.*'
"type: revert ↩️":
  title: '^revert(\(.+\))?:.*'
"type: localize 🌐":
  title: '^localize(\(.+\))?:.*'
"type: bump 📦":
  title: '^bump(\(.+\))?:.*'
