services:
  valkey:
    container_name: valkey
    image: valkey/valkey:8.1-alpine
    ports:
      - 6379:6379
    volumes:
      - valkey-data:/data
    networks:
      - mcp-server-playground
    restart: unless-stopped
    command: --save 60 1 --loglevel debug

  mcp-server-playground:
    container_name: mcp-server-playground
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 3000:3000
    networks:
      - mcp-server-playground
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - $MCP_CONFIG_TOOLS_PROJECT_PATH:$MCP_CONFIG_TOOLS_PROJECT_PATH
    working_dir: /app
    command: npm run dev

volumes:
  valkey-data:
    driver: local

networks:
  mcp-server-playground:
    driver: bridge
